### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by rchen8** [zokeber/docker-postgresql#1]
I'm trying to perform the same functionality of `docker run -d -p 5432:5432 --name postgresql94 zokeber/postgresql94 && docker exec -it postgresql94 psql` using `docker-compose`.

This is my `docker-compose.yml` file:
```
version: '3'
services:
  postgresql94:
    command: ["/bin/bash", "-c", "psql"]
    image: zokeber/postgresql94:latest
    hostname: postgresql94
    build: .
    ports:
      - 5432:5432
```

Yet when I run `docker-compose up` I get the following error message:
```
Creating compose_postgresql94_1 ... 
Creating compose_postgresql94_1 ... done
Attaching to compose_postgresql94_1
postgresql94_1  | psql: could not connect to server: No such file or directory
postgresql94_1  | 	Is the server running locally and accepting
postgresql94_1  | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
compose_postgresql94_1 exited with code 2
```

What am I missing?
